### ISSUE TITLE
CRS was removed from the spec

### ISSUE THREAD

**Issue by jmarca** [mgold/elm-geojson#1]
Hi, looks good but I haven't actually used it yet.

One issue, in my mailing list post I linked to an older version of the spec, and while working on it I noticed that it was deprecated in favor of the official one:  https://tools.ietf.org/html/rfc7946

In the official spec, CRS has been removed, and all GeoJSON objects are expected to use the WGS84 CRS:  https://tools.ietf.org/html/rfc7946#section-4

So I think the maybe CRS and associated tests need to be removed.

I'd fork and pull-request, but my Elm skills are _really_ weak at this point...

**Comment by mgold** [comment]
No worries! Yeah one of things I need to do before release is go through the RFC and see what other changes there are.
